# Generated by Django 4.2.7 on 2024-01-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="timestamp",
            field=models.DateTimeField(default=None),
        ),
    ]
