# Generated by Django 4.2.7 on 2024-01-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bids_timestamp"),
    ]

    operations = [
        migrations.RenameModel(old_name="Bids", new_name="Bid",),
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
        migrations.RenameModel(old_name="Listings", new_name="Listing",),
    ]
