# Generated by Django 4.2.7 on 2024-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_bids_bid_rename_comments_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="price", new_name="startingBid",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
