# Generated by Django 4.2.7 on 2024-01-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_price_listing_startingbid_listing_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(default=None),
        ),
    ]
