# Generated by Django 4.2.7 on 2024-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_user_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
