# Generated by Django 4.2.7 on 2024-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_bid_item_alter_bid_user_alter_comment_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(default="No Category Listed", max_length=50),
        ),
    ]
