# Generated by Django 4.2.7 on 2024-01-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_user_watchlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="watchlist",),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlists", to="auctions.listing"
            ),
        ),
    ]
