# Generated by Django 4.2.7 on 2024-01-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_listing_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="winner",
            field=models.CharField(default="", max_length=50),
        ),
    ]
