# Generated by Django 4.2.7 on 2024-01-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_listing_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="winner",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
